import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
 const sidebars: SidebarsConfig = {
  notes: [
    {
      type: 'category',
      label: '筆記',
      link: {
        type: 'doc',
        id: 'notes/index', // 📄 對應 /docs/notes/index.mdx
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'notes',
        },
      ],
    },
  ],
  series: [
    {
      type: 'category',
      label: '系列文章',
      link: {
        type: 'doc',
        id: 'series/index', // 📄 對應 /docs/series/index.mdx
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'series',
        },
      ],
    },
  ],
};

export default sidebars;
